### ISSUE TITLE
Introduction to Controls - Getting to know your Simulator

### ISSUE THREAD

**Issue by cornzyblack** [udacity/robotics-beta-test-issues#595]
I receive some error messages when trying to test run the default code. Is this normal?

**Comment by cornzyblack** [comment]
`Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_eplqjiqolx/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_eplqjiqolx/studentMain.py", line 63, in <module>
    import hover_plot
  File "/tmp/vmuser_eplqjiqolx/hover_plot.py", line 71, in <module>
    ax3.plot(time, controller.effort_applied, label='effort', linewidth=3, color = 'red')
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/axes/_axes.py", line 1406, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/axes/_base.py", line 407, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/axes/_base.py", line 385, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/axes/_base.py", line 244, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (500,) and (501,)`

![capture](https://user-images.githubusercontent.com/5692718/29244226-ae1acb58-7faa-11e7-97d1-3ac3bfe86a5d.PNG)

**Comment by kylesf** [comment]
Try refreshing the browser and resetting the quiz. Please :)

**Comment by cornzyblack** [comment]
I've done both of that but get the same error. (I use Chrome)

**Comment by kylesf** [comment]
Hmm, let me test with my student account in chrome.

**Comment by kylesf** [comment]
Squashed the bug! Thanks for reporting. Let me know if it works for you now.

**Comment by cornzyblack** [comment]
Ok, I just refreshed now and tried it again, the error is gone now :)

**Comment by kylesf** [comment]
Cool. Thanks again!
