### ISSUE TITLE
Introduction to Controls - Building a PI controller

### ISSUE THREAD

**Issue by cornzyblack** [udacity/robotics-beta-test-issues#597]
`Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_ooaxomltfy/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_ooaxomltfy/studentMain.py", line 63, in <module>
    import hover_plot
  File "/tmp/vmuser_ooaxomltfy/hover_plot.py", line 56, in <module>
    y = ydot(y,t,pid)
NameError: name 'pid' is not defined`

A fix, change ine 56 in **hover_plot.py** to
`y = ydot(y,t , pi)`

**Comment by kylesf** [comment]
Fixed, thanks!
